name: load cra template

on:
  schedule:
  - cron: 0 20 * * 0-6

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: create a template with create-react-app
      run: |
        npx create-react-app cra
